# UFC Descriptive Statistics

## List of Contents:
## 01. Import Libraries
## 02. Import Data
## 03. Descriptive Statistics


## --

## 01. Import Libraries

In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import os

## 02. Import Data

In [2]:
#Defining path for data import
path = r'C:\Users\Mosspants\Desktop\CareerFoundry\A6_Advanced Analytics & Dashboard Design\UFC_Project\02_Data'

In [3]:
#Importing data
df_ufc = pd.read_csv(os.path.join(path, 'Prepared_Data', 'ufc_cleaned.csv'), index_col = False)

In [4]:
#Checking import
df_ufc.head()

,Unnamed: 0,R_fighter,B_fighter,Referee,location,Winner,title_bout,weight_class,B_total_time_fought(seconds),B_total_rounds_fought,...,R_win_by_TKO_Doctor_Stoppage,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age,Day,Month,Year
0,0,Adrian Yanez,Gustavo Lopez,Chris Tognoni,"Las Vegas, Nevada, USA",Red,False,Bantamweight,531.5000,4,...,0,Orthodox,170.18,177.80,135.0,31.0,27.0,20,3,2021
1,1,Trevin Giles,Roman Dolidze,Herb Dean,"Las Vegas, Nevada, USA",Red,False,Middleweight,577.5000,4,...,0,Orthodox,182.88,187.96,185.0,32.0,28.0,20,3,2021
2,2,Tai Tuivasa,Harry Hunsucker,Herb Dean,"Las Vegas, Nevada, USA",Red,False,Heavyweight,643.9375,0,...,0,Southpaw,187.96,190.50,264.0,32.0,28.0,20,3,2021
3,3,Cheyanne Buys,Montserrat Conejo,Mark Smith,"Las Vegas, Nevada, USA",Blue,False,WomenStrawweight,643.9375,0,...,0,Switch,160.02,160.02,115.0,28.0,25.0,20,3,2021
4,4,Marion Reneau,Macy Chiasson,Mark Smith,"Las Vegas, Nevada, USA",Blue,False,WomenBantamweight,764.0000,11,...,0,Orthodox,167.64,172.72,135.0,29.0,43.0,20,3,2021

## 03. Descriptive Statistics

In [5]:
#Using describe to get statistics
df_ufc.describe()

,Unnamed: 0,B_total_time_fought(seconds),B_total_rounds_fought,B_total_title_bouts,B_current_win_streak,B_current_lose_streak,B_longest_win_streak,B_wins,B_losses,B_draw,...,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age,Day,Month,Year
count,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.0,...,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000,5809.000000
mean,2904.000000,623.295178,9.713892,0.278189,0.956275,0.407127,1.658977,2.639008,1.579274,0.0,...,0.799966,0.069375,178.812240,183.508332,169.105182,29.299191,29.623860,15.487519,6.710621,2013.967809
std,1677.058188,226.262011,11.979555,1.138970,1.497294,0.671403,1.816544,3.346342,1.956031,0.0,...,1.360701,0.274941,8.846186,10.391097,34.675301,4.023177,4.156361,8.546576,3.455456,4.674254
min,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,152.400000,152.400000,115.000000,18.000000,19.000000,1.000000,1.000000,2000.000000
25%,1452.000000,497.750000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,172.720000,177.800000,145.000000,26.000000,27.000000,8.000000,4.000000,2011.000000
50%,2904.000000,643.937500,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.0,...,0.000000,0.000000,180.340000,182.880000,170.000000,29.000000,29.000000,16.000000,7.000000,2015.000000
75%,4356.000000,787.910515,14.000000,0.000000,1.000000,1.000000,3.000000,4.000000,2.000000,0.0,...,1.000000,0.000000,185.420000,190.500000,185.000000,32.000000,32.000000,22.000000,10.000000,2018.000000
max,5808.000000,1500.000000,94.000000,16.000000,16.000000,5.000000,16.000000,23.000000,16.000000,0.0,...,13.000000,2.000000,210.820000,213.360000,280.000000,47.000000,47.000000,31.000000,12.000000,2021.000000

In [9]:
#Assigning output of describe
stats = df_ufc.describe()

In [10]:
#Exporting to clipboard
stats.to_clipboard()

In [11]:
#Mode for Referee
df_ufc['Referee'].mode()

0    Herb Dean
Name: Referee, dtype: object

In [12]:
#Mode for location
df_ufc['location'].mode()

0    Las Vegas, Nevada, USA
Name: location, dtype: object

In [13]:
#Mode for weight_class
df_ufc['weight_class'].mode()

0    Welterweight
Name: weight_class, dtype: object

In [14]:
#Mode for B_Stance
df_ufc['B_Stance'].mode()

0    Orthodox
Name: B_Stance, dtype: object

In [15]:
#Mode for R_Stance
df_ufc['R_Stance'].mode()

0    Orthodox
Name: R_Stance, dtype: object

### No changes made to data, no need to export.